### ISSUE TITLE
convert the user inputted time to millisecondsSinceEpoch

### ISSUE THREAD

**Issue by muktabd** [muktaahammed/DateTime-Convert-into-millisecondsSinceEpoch-in-Flutter#1]
I couldn't convert the user inputted time to millisecondsSinceEpoch. For example : 20 09 2020 9 30 will be 1600662707 something like this.

**Comment by muktabdinfo** [comment]
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:intl/intl.dart';
import 'package:datetime_picker_formfield/datetime_picker_formfield.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  // This widget is the root of your application.
  _timeDateConvertToMili createState() => _timeDateConvertToMili();
}

class _timeDateConvertToMili extends State<MyApp>{

  final format = DateFormat('yyyy-MM-dd HH:mm');
  final initialValue = DateTime.now();

  bool autoValidate = false;
  bool showResetIcon = true;
  DateTime value = DateTime.now();

  final startTimeController = TextEditingController();
  final endTimeController = TextEditingController();

  @override
  void dispose() {
    startTimeController.dispose();
    endTimeController.dispose();
    super.dispose();
  }


  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Container(
          child: Column(
            children: [
              SizedBox(height: 50,),

              Container(
                padding: EdgeInsets.all(5.0),
                decoration: BoxDecoration(
                    border: Border(
                      // bottom: BorderSide(color: Colors.grey[100])
                    )),
                child: DateTimeField(
                  decoration: InputDecoration(
                    border: OutlineInputBorder(),
                    labelText: 'Start Time',
                    labelStyle: TextStyle(color: Colors.black),
                  ),
                  style: TextStyle(
                    color: Colors.black,
                  ),
                  controller: startTimeController,
                  format: format,
                  onShowPicker: (context, currentValue) async {
                    final date = await showDatePicker(
                        context: context,
                        firstDate: DateTime(2000),
                        initialDate: currentValue ?? DateTime.now(),
                        lastDate: DateTime(2100));
                    if (date != null) {
                      final time = await showTimePicker(
                        context: context,
                        initialTime:
                        TimeOfDay.fromDateTime(currentValue ?? DateTime.now()),
                      );
                      return DateTimeField.combine(date, time);
                    } else {
                      return currentValue;
                    }
                  },
                  resetIcon: showResetIcon ? Icon(Icons.delete) : null,
                ),
              ),
              Container(
                padding: EdgeInsets.all(5.0),
                decoration: BoxDecoration(
                    border: Border(
                      // bottom: BorderSide(color: Colors.grey[100])
                    )),
                child: DateTimeField(
                  decoration: InputDecoration(
                    border: OutlineInputBorder(),
                    labelText: 'End Time',
                    labelStyle: TextStyle(color: Colors.black),
                  ),
                  style: TextStyle(
                    color: Colors.black,
                  ),

                  controller: endTimeController,
                  format: format,
                  onShowPicker: (context, currentValue) async {
                    final date = await showDatePicker(
                        context: context,
                        firstDate: DateTime(2000),
                        initialDate: currentValue ?? DateTime.now(),
                        lastDate: DateTime(2100));
                    if (date != null) {
                      final time = await showTimePicker(
                        context: context,
                        initialTime:
                        TimeOfDay.fromDateTime(currentValue ?? DateTime.now()),
                      );
                      return DateTimeField.combine(date, time);
                    } else {
                      return currentValue;
                    }
                  },
                  resetIcon: showResetIcon ? Icon(Icons.delete) : null,
                ),
              ),

              Container(
                child: RaisedButton(
                  onPressed: () { 
                    convertNow();
                  },
                  child: Text('Convert to Epoch'),
                ),
              ),
              SizedBox(height: 30,),

              Text('View your Inputted Data'),
              Padding(
                padding: const EdgeInsets.all(16.0),
                child: Text(
                  startTimeController.text,
                ),
              ),
              Padding(
                padding: const EdgeInsets.all(6.0),
                child: Text(
                  endTimeController.text,
                ),
              ),
            ],
          ),

        ),
      ),
    );
  }

  void convertNow() {

    var inputedStartTime = DateTime.parse(startTimeController.text);
    var mili = inputedStartTime.millisecondsSinceEpoch/1000;
    var startTime = mili.toInt();

    var inputedEndtTime = DateTime.parse(startTimeController.text);
    var mili2 = inputedEndtTime.millisecondsSinceEpoch/1000;
    var endTime = mili2.toInt();

    print ('Converted start time is $startTime');
    print ('Converted end time is $endTime');

  }

}

**Comment by muktabdinfo** [comment]
**Here is the answer. What you are looking for. Hope it will works.**

**Comment by engr-muktaahmed** [comment]
var inputedStartTime = DateTime.parse(startTimeController.text);
var mili = inputedStartTime.millisecondsSinceEpoch/1000;
var startTime = mili.toInt();

var inputedEndtTime = DateTime.parse(endTimeController.text);
var mili2 = inputedEndtTime.millisecondsSinceEpoch/1000;
var endTime = mili2.toInt();

print ('Converted start time is $startTime');
print ('Converted end time is $endTime');
